# Generated by Django 5.0.3 on 2024-03-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='written_by',
            field=models.CharField(default='default user', max_length=50),
        ),
    ]
